In [1]:
print("string in Jupyter")

string in Jupyter


In [5]:
2+2

4

In [2]:
"hello"

'hello'

# текст в разметке markdown  (H1) ставится "#"

## - массивы (H2)


In [1]:
# установка numpy
!pip install numpy

In [76]:
import numpy as np

## линейная алгебра

   
   # создание

In [10]:
# создание из списка
myList = [1,2,3,4]
myList

[1, 2, 3, 4]

In [12]:
np.array(myList)


array([1, 2, 3, 4])

In [13]:
myArray = np.array(myList)

In [14]:
myArray

array([1, 2, 3, 4])

In [16]:
# создание массива из нулей
z = np.zeros(10) #сколько требуется значений в массиве
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
z.dtype

dtype('float64')

In [20]:
np.zeros(10, dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [21]:
np.zeros(10, dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [22]:
np.zeros(10,dtype="int").dtype

dtype('int32')

In [23]:
# 2-мерный массив с формой 2 на 3 (2 строки и 3 столбца)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# 3-мерный массив
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# линейная последовательность
np.arange(0,20,2) # диапазон от 0 до 20 с шагом 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.arange(0,20,2).reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [38]:
# вектор как массив из равномерно распределенных значений
# например, от 0 до 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [40]:
# создание массива со случайными значениями
# массив размером 3 * 5
# случайные значения из равномерно распределенного диапазона от 0 до 1
np.random.random(5) #скаляр

array([0.34812398, 0.25314868, 0.07770594, 0.15149272, 0.5218957 ])

In [41]:
np.random.random((3,5)) # кортеж

array([[0.14510295, 0.88285374, 0.19833904, 0.52091923, 0.13373895],
       [0.48165824, 0.94101404, 0.035713  , 0.87804099, 0.87448559],
       [0.96727086, 0.08266224, 0.82090403, 0.81407301, 0.31347224]])

In [47]:
np.random.random((3,5)).astype("float16")

array([[0.7705, 0.6533, 0.7563, 0.546 , 0.981 ],
       [0.9487, 0.5933, 0.3757, 0.4832, 0.987 ],
       [0.1096, 0.2588, 0.4883, 0.5527, 0.2969]], dtype=float16)

In [48]:
np.random.random((3,5)).astype("float64")


array([[0.62468219, 0.52938769, 0.6658724 , 0.04227593, 0.69795104],
       [0.79724847, 0.62387693, 0.63721785, 0.45985233, 0.1144899 ],
       [0.71311032, 0.6596328 , 0.57471836, 0.27754952, 0.24282697]])

In [49]:
# создание массива с целочисленными случайными значениями
np.random.randint(10)

9

In [50]:
np.random.randint(10,20)

10

In [52]:
np.random.randint(10, size=5)

array([3, 8, 0, 0, 2])

In [53]:
np.random.randint(10,size=(2,3))

array([[9, 0, 0],
       [3, 6, 7]])

In [54]:
np.random.randint(10,20, size=(2,3))

array([[18, 16, 17],
       [16, 17, 16]])

##  аттрибуты

In [56]:
a1 = np.random.randint(10,20, size=(3,5))
a1

array([[18, 18, 10, 16, 15],
       [12, 17, 18, 16, 12],
       [10, 17, 13, 10, 13]])

In [57]:
# размерность массива (кол-во измерений/осей)   a1 - тензор 2
a1.ndim

2

In [58]:
# форма массива
a1.shape

(3, 5)

In [59]:
# размерность массива (кол-во всех элементов массива)
a1.size

15

In [60]:
# тип значений массива
a1.dtype    #a1 - 32битный тип

dtype('int32')

## индексация

In [61]:
a2 = np.random.randint(20, size=10)
a2

array([ 4, 19, 15,  1,  3, 13,  1, 12,  2,  2])

In [62]:
a2[0]

4

In [63]:
a2[-1]

2

In [70]:
a3 = np.random.randint(10, size=(2,3))
a3

array([[8, 1, 8],
       [8, 7, 0]])

In [73]:
#a3[0][1]
a3[0,1]

1

- срезы

In [65]:
a2[:5]

array([ 4, 19, 15,  1,  3])

In [66]:
a2[1:]

array([19, 15,  1,  3, 13,  1, 12,  2,  2])

In [67]:
a2[1:3]

array([19, 15])

In [68]:
a2[1:6:2]  # с шагом 2

array([19,  1, 13])

In [74]:
a3[0, 1:]

array([1, 8])

In [75]:
a3[:, 1:]

array([[1, 8],
       [7, 0]])

# НОВЫЙ УРОК 

- представления (views) и копии (copies)

In [41]:
# срез списка
my_list = [1,2,3,4,5]
slice = my_list[2:]

In [42]:
slice is my_list

False

In [43]:
slice[-1] = 100

In [44]:
slice

[3, 4, 100]

In [45]:
my_list

[1, 2, 3, 4, 5]

In [63]:
my_list


[1, 2, 3, 4, 5]

In [64]:
# срез массива
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [65]:
sub_arr = my_array[2:]
sub_arr

array([3, 4, 5])

In [66]:
sub_arr is my_array

False

In [67]:
# массив созданный срезом из другого массива является представлением
sub_arr[-1] = 500
sub_arr

array([  3,   4, 500])

In [68]:
my_array

array([  1,   2,   3,   4, 500])

In [70]:
# копия массива
sub_arr2 = my_array[2:].copy()
sub_arr2

array([  3,   4, 500])

In [71]:
sub_arr2[-1] = 100
sub_arr2

array([  3,   4, 100])

In [72]:
my_array

array([  1,   2,   3,   4, 500])

- изменение формы

In [77]:
# 1-мерный массив (вектор-строка)
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
# проверка формы массива
arr.shape

(9,)

In [79]:
# создание вектор-столбца
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [82]:
# создание 2-мерного массива
my_shape = (3,3) # - кортеж со значениями формы будущего массива (кол-во строк, кол-во столбцов)
arr.reshape(my_shape)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Операции (Универсальные функции)

In [84]:
a = np.arange(5)
b = np.arange(1,6)
print(a)
print(b)

[0 1 2 3 4]
[1 2 3 4 5]


In [85]:
# поэлементное деление
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [86]:
# адаптер (алиас) оператора "+"
np.add(a, b)

array([1, 3, 5, 7, 9])

- аггрегирование

In [87]:
# аггрегирование - это вычисление неких сводных показателей
arr_2 = np.random.random(10)
arr_2

array([0.95764784, 0.86643484, 0.49989091, 0.69354237, 0.71520511,
       0.39973794, 0.33069835, 0.95285877, 0.22645215, 0.25576772])

In [89]:
# сумма
#np.sum(arr_2) # 1D array
np.sum(arr.reshape(3,3)) # 2D array

45

In [95]:
# минимум и максимум
np.min(arr_2), np.max(arr_2)

(0.226452153496573, 0.9576478361294314)

In [100]:
print(f"arr: {np.min(arr_2)}")

arr: 0.226452153496573


- сравнения

In [99]:
np.array([1,2,3]) >= 2

array([False,  True,  True])

In [105]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# имеются ли в массиве какие-либо значения, превышающие 5

np.any(x > 5)

True

In [109]:
np.any(x > 5, axis=0) # по столбцу, а при axis=1 по строкам

array([ True,  True,  True])

In [110]:
# все ли значения равны 6
np.all(x < 5, axis=1)

array([ True, False, False])

- маскирование

In [117]:
# x = np.array([1,2,3,4,5])
x = np.random.randint(10, size=(5,))
x < 3

array([False,  True,  True, False, False])

In [118]:
y = np.array([10,20,30,40,50])
y[x < 3] # массив из булевых значений (например x < 3) - маска

array([20, 30])

In [119]:
x[x < 3]

array([1, 0])

- прихотливая индексация

In [134]:
x = np.random.randint(100, size=10)
x

array([39, 88, 34, 82, 67, 25, 23, 18, 58, 32])

In [135]:
# передаем список или массив индексов необходимых значений
x[[3,0,5]]

array([82, 39, 25])

In [138]:
# если хотим массив по форме массива индексов, то нужно обязательно отправить массив numpy ( np."massiv"([]) )
ind = np.array([
    [3,0],
    [1,2]
])
x[ind]

array([[82, 39],
       [88, 34]])